version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: conserjeria
      DB_PLATFORM: sqlite
      DB_DDL_MODE: dropCreate
      DB_NAME: conserjeria
      DB_URL: jdbc:sqlite:conserjeria.db
    restart: always